# Generated by Django 2.1.3 on 2018-11-10 20:41

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('session_id', models.CharField(max_length=400)),
                ('user_name', models.CharField(max_length=50)),
                ('jobcoach_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')], default=1)),
                ('emotion', models.PositiveSmallIntegerField(choices=[(1, 'Frustado'), (2, 'Triste'), (1, 'Irritado')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
