# Generated by Django 2.1.3 on 2018-11-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='emotion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Frustado'), (2, 'Triste'), (1, 'Irritado')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='jobcoach_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='session_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
