# Generated by Django 2.1.3 on 2018-11-10 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181110_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datauser',
            old_name='user_email',
            new_name='email',
        ),
    ]
