# Generated by Django 2.1.3 on 2018-11-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181110_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datauser',
            old_name='emotion',
            new_name='emotion_neg',
        ),
        migrations.RenameField(
            model_name='datauser',
            old_name='gender',
            new_name='user_gender',
        ),
    ]
