# Generated by Django 2.1.3 on 2018-11-11 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181110_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEmotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('emotion_pos', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Feliz'), (2, 'Emocionado'), (3, 'Frustado'), (4, 'Triste'), (5, 'Irritado')], default=1, null=True)),
                ('emotion_neg', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Feliz'), (2, 'Emocionado'), (3, 'Frustado'), (4, 'Triste'), (5, 'Irritado')], default=3, null=True)),
                ('first_obstacle', models.TextField(blank=True, max_length=500, null=True, verbose_name='First Obstacle')),
                ('alerts_total', models.CharField(blank=True, max_length=10, null=True, verbose_name='Alerts Total')),
                ('alerts_critical', models.CharField(blank=True, max_length=10, null=True, verbose_name='Alerts Criticals')),
                ('alerts_non_critical', models.CharField(blank=True, max_length=10, null=True, verbose_name='Alerts Non-Critial')),
                ('work_dislike', models.TextField(blank=True, max_length=500, null=True, verbose_name='Work Dislike')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DataUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
