# Generated by Django 2.1.3 on 2018-11-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181111_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyemotions',
            old_name='emotion_pos',
            new_name='emotions_pos',
        ),
    ]
