# Generated by Django 2.1.3 on 2018-11-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181111_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemotions',
            name='data_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.DataUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyemotions',
            name='session_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
