# Generated by Django 2.1.3 on 2018-11-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181111_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyemotions',
            name='data_user',
        ),
    ]
