# Generated by Django 2.1.3 on 2018-11-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_dailyemotions_initial_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyemotions',
            old_name='first_obstacle',
            new_name='first_problem',
        ),
    ]
