# Generated by Django 2.1.3 on 2018-11-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181111_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyemotions',
            old_name='work_dislike',
            new_name='second_dislike',
        ),
    ]
