# Generated by Django 2.1.3 on 2018-11-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_datauser_slack'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemotions',
            name='slack',
            field=models.CharField(default='', max_length=140, verbose_name='Slack ID'),
            preserve_default=False,
        ),
    ]
